name: ParkourSystem
version: 1.0  # Replace this with the actual version number of your plugin
main: org.vexylon.parkoursystem.Main
api-version: '1.8'

commands:
  setjoin:
    description: Sets the join location for ParkourSystem
  parkour:
    description: yeah ok