name: ParkourSystem
version: 1.0
main: org.vexylon.parkoursystem.Main
api-version: '1.8'

commands:
  setjoin:
    description: Sets the join location for ParkourSystem
  parkour:
    description: yeah ok
